#!/usr/bin/env node
// Pulls the current teams and event assignments from the TeamFit Team Builder (Google Apps Script
// backend, read-only `load` action) and rewrites assets/js/roster-2027.js.
//
//   node tools/sync-teamfit.mjs            fetch live data
//   node tools/sync-teamfit.mjs load.json  use a saved `load` response instead
//
// Only first names (plus a last initial when two members share a first name), teams, and events are
// written. Emails, grades, and survey answers stay in the Team Builder.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const API_URL = 'https://script.google.com/macros/s/AKfycbxU5Tqy01vPzoW3yJ7Ww5Pv54D-8SVV7m8AoNdepanfPnzD4xDNzW4DBXTdh6HOgzdC/exec';
const API_TOKEN = 'Riverdale5250';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outFile = path.join(root, 'assets/js/roster-2027.js');

async function loadData() {
  if (process.argv[2]) return JSON.parse(fs.readFileSync(process.argv[2], 'utf8'));
  const res = await fetch(`${API_URL}?${new URLSearchParams({ token: API_TOKEN, action: 'load' })}`);
  const text = await res.text();
  try { return JSON.parse(text); }
  catch { throw new Error(`Team Builder did not return JSON (HTTP ${res.status}). Check the deployment URL.`); }
}

// "Theo, Schwider" → ["Theo", "Schwider"]
function splitName(raw) {
  const parts = String(raw || '').replace(/[,]+/g, ' ').trim().split(/\s+/).filter(Boolean);
  return parts.map(p => p[0].toUpperCase() + p.slice(1));
}

const data = await loadData();
if (!data.ok) throw new Error(`Team Builder error: ${data.error || 'unknown'}`);

const { state, responses, events } = data;
const byEmail = new Map(responses.map(r => [r.email, r]));
const teams = data.teams || ['A', 'B', 'C'];

const placed = Object.entries(state.members || {})
  .filter(([email, m]) => teams.includes(m.team) && byEmail.has(email));
const firstCounts = {};
placed.forEach(([email]) => {
  const first = splitName(byEmail.get(email).name)[0];
  firstCounts[first] = (firstCounts[first] || 0) + 1;
});
const displayName = new Map(placed.map(([email]) => {
  const [first, ...rest] = splitName(byEmail.get(email).name);
  const last = rest.at(-1);
  return [email, firstCounts[first] > 1 && last ? `${first} ${last[0]}.` : first];
}));

const roster = {};
const assignments = {};
for (const team of teams) {
  roster[team] = placed.filter(([, m]) => m.team === team).map(([email]) => displayName.get(email))
    .sort((a, b) => a.localeCompare(b));
  assignments[team] = {};
  for (const ev of events) {
    assignments[team][ev.name] = ((state.assignments?.[team] || {})[ev.name] || [])
      .filter(email => displayName.has(email) && state.members[email].team === team)
      .map(email => displayName.get(email));
  }
}

const slotsTotal = events.reduce((n, ev) => n + ev.slots, 0);
const meta = {
  source: 'TeamFit Team Builder',
  version: data.version,
  updatedAt: data.updatedAt,
  syncedAt: new Date().toISOString(),
  published: Boolean(state.published),
  slotsPerTeam: slotsTotal,
  unplaced: responses.filter(r => !teams.includes(state.members?.[r.email]?.team)).length
};

const js = `// 2026–27 teams and event assignments. GENERATED by tools/sync-teamfit.mjs from the TeamFit Team Builder —
// do not edit by hand; change the Team Builder and re-run \`node tools/sync-teamfit.mjs\`.
const ROSTER_2027_META = ${JSON.stringify(meta, null, 2)};

const ROSTER_2027 = ${JSON.stringify(roster, null, 2)};

const ASSIGNMENTS_2027 = ${JSON.stringify(assignments, null, 2)};
`;
fs.writeFileSync(outFile, js);

console.log(`Team Builder v${meta.version} (saved ${meta.updatedAt})${meta.published ? '' : ' — not marked published'}`);
for (const team of teams) {
  const filled = Object.values(assignments[team]).reduce((n, a) => n + a.length, 0);
  console.log(`  Team ${team}: ${roster[team].length} members, ${filled}/${slotsTotal} slots`);
}
if (meta.unplaced) console.log(`  ${meta.unplaced} respondent(s) not on a team`);
console.log(`Wrote ${path.relative(root, outFile)}`);
